# Generated by Django 3.2.5 on 2021-11-04 06:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='margin_policy',
            field=jsonfield.fields.JSONField(blank=True, default={'CLIENTADMIN': True, 'LEVEL_1': True, 'LEVEL_2': True, 'SELF_BOUGHT': {'APPLY': False, 'LIMIT': 3}, 'SUPERADMIN': False, 'USER_SELF': True}, null=True),
        ),
    ]
