# Generated by Django 3.2.5 on 2021-11-01 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning')], default='info', max_length=32)),
                ('target', models.IntegerField(default=0)),
                ('broadcast_on', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('hyper_link', models.TextField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-broadcast_on'],
            },
        ),
    ]
