# Generated by Django 3.2.5 on 2021-11-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pare', models.CharField(default='USD/JPY', max_length=10)),
                ('bid', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('ask', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('high', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('low', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
