# Generated by Django 3.2.5 on 2021-11-02 06:49

from django.db import migrations, models
import jsonfield.fields
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='type',
            field=models.CharField(choices=[('BS', 'BUY STOCK'), ('RS', 'RETURN STOCK'), ('OC', 'ORDER CANCELLED'), ('OU', 'ORDER USED')], default='OU', max_length=28),
        ),
        migrations.AlterField(
            model_name='pingoitem',
            name='point_rule',
            field=jsonfield.fields.JSONField(blank=True, default=store.models.default_point_rule, null=True),
        ),
        migrations.AlterField(
            model_name='pingoorder',
            name='delivery_info',
            field=jsonfield.fields.JSONField(blank=True, default=store.models.default_delivery_info, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
