# Generated by Django 3.2.5 on 2021-11-04 06:23

from django.db import migrations, models
import jsonfield.fields
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211102_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsliderimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='type',
            field=models.CharField(choices=[('RS', 'RETURN STOCK'), ('OU', 'ORDER USED'), ('BS', 'BUY STOCK'), ('OC', 'ORDER CANCELLED')], default='OU', max_length=28),
        ),
        migrations.AlterField(
            model_name='pingoitem',
            name='point_rule',
            field=jsonfield.fields.JSONField(blank=True, default=store.models.default_point_rule, null=True),
        ),
        migrations.AlterField(
            model_name='pingoitem',
            name='video_url',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pingoorder',
            name='delivery_info',
            field=jsonfield.fields.JSONField(blank=True, default=store.models.default_delivery_info, null=True),
        ),
    ]
