# Generated by Django 3.2.5 on 2021-11-08 12:02

from django.db import migrations, models
import jsonfield.fields
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211104_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='type',
            field=models.CharField(choices=[('OC', 'ORDER CANCELLED'), ('OU', 'ORDER USED'), ('RS', 'RETURN STOCK'), ('BS', 'BUY STOCK')], default='OU', max_length=28),
        ),
        migrations.AlterField(
            model_name='pingoitem',
            name='point_rule',
            field=jsonfield.fields.JSONField(blank=True, default=store.models.default_point_rule, null=True),
        ),
        migrations.AlterField(
            model_name='pingoorder',
            name='delivery_info',
            field=jsonfield.fields.JSONField(blank=True, default=store.models.default_delivery_info, null=True),
        ),
    ]
