# Generated by Django 3.2.5 on 2021-11-09 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import store.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_auto_20211108_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='store.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='type',
            field=models.CharField(choices=[('OU', 'ORDER USED'), ('OC', 'ORDER CANCELLED'), ('BS', 'BUY STOCK'), ('RS', 'RETURN STOCK')], default='OU', max_length=28),
        ),
        migrations.AlterField(
            model_name='pingoitem',
            name='point_rule',
            field=jsonfield.fields.JSONField(blank=True, default=store.models.default_point_rule, null=True),
        ),
        migrations.AlterField(
            model_name='pingoorder',
            name='delivery_info',
            field=jsonfield.fields.JSONField(blank=True, default=store.models.default_delivery_info, null=True),
        ),
    ]
