# Generated by Django 3.2.5 on 2021-11-23 05:49

from django.db import migrations, models
import jsonfield.fields
import store.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211123_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='type',
            field=models.CharField(choices=[('OU', 'ORDER USED'), ('BS', 'BUY STOCK'), ('OC', 'ORDER CANCELLED'), ('RS', 'RETURN STOCK')], default='OU', max_length=28),
        ),
        migrations.AlterField(
            model_name='pingoorder',
            name='delivery_info',
            field=jsonfield.fields.JSONField(blank=True, default=store.models.products.default_delivery_info, null=True),
        ),
    ]
