# Generated by Django 3.2.5 on 2022-03-14 00:09

from django.db import migrations, models
import jsonfield.fields
import store.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211123_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='type',
            field=models.CharField(choices=[('BS', 'BUY STOCK'), ('OU', 'ORDER USED'), ('RS', 'RETURN STOCK'), ('OC', 'ORDER CANCELLED')], default='OU', max_length=28),
        ),
        migrations.AlterField(
            model_name='pingoorder',
            name='delivery_info',
            field=jsonfield.fields.JSONField(blank=True, default=store.models.products.default_delivery_info, null=True),
        ),
    ]
