# Generated by Django 3.2.5 on 2022-03-14 00:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import store.models.orders


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220314_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_info',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='logistic',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='paid_info',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_info',
            field=jsonfield.fields.JSONField(blank=True, default=store.models.orders.default_delivery_info, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='logistic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.logistic'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='type',
            field=models.CharField(choices=[('BS', 'BUY STOCK'), ('OU', 'ORDER USED'), ('RS', 'RETURN STOCK'), ('OC', 'ORDER CANCELLED')], default='OU', max_length=28),
        ),
    ]
